spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: bootuser
    password: bootuser
    url: jdbc:mariadb://localhost:3308/myinstagram

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        default_batch_fetch_size: 100
        format_sql: true
        use_sql_comments: true
    open-in-view: true

  profiles:
    active: local

#  jackson:
#    serialization:
#      FAIL_ON_EMPTY_BEANS: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB

  security:
    user:
      name: test
      password: 1234

logging:
  level:
    org.hibernate.SQL: debug

file:
  path: C:/study/image/
